### ISSUE TITLE
Create enhanced form

### ISSUE THREAD

**Issue by LOGESH-B** [LOGESH-B/ChromeLandingPage#1]
Create a form which gets the link and link of the image

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by LOGESH-B** [comment]
@Pulkitxm sure,
It is a simple HTML,JavaScript only project for the custom landingpage on chrome page

on clicking the + button on the bottom form will appear
Currently the form is getting only  title and logo link.You need to add another input to get the url of the site and add it in anchor tag.which will be displayed at the bottom of the page
