### ISSUE TITLE
[Feature 🧑‍💻] Swap between Search engine

### ISSUE THREAD

**Issue by LOGESH-B** [LOGESH-B/ChromeLandingPage#14]
Hii **Contributors**,

Here a next feature of our project 
* Switch between the search engines
* Your Ideas are also welcomed

![image](https://github.com/LOGESH-B/ChromeLandingPage/assets/86541143/be206694-602c-443b-acb7-79695fb3447e)
![image](https://github.com/LOGESH-B/ChromeLandingPage/assets/86541143/95919555-732c-401a-87d8-2c957ec685d9)

🔴 On Clicking on the swap the search Engine needs to be changed
🔴 Change also occured at the search field  aswell

**Comment by MRodriguez-M** [comment]
Can you assign this one to me? I want to work on this issue

**Comment by LOGESH-B** [comment]
@MRodriguez-M  
Yeah sure.

**Comment by LOGESH-B** [comment]
Thanks for your Contribution✌️
