### ISSUE TITLE
[Feature] Time and Date

### ISSUE THREAD

**Issue by LOGESH-B** [LOGESH-B/ChromeLandingPage#6]
Hii Contributors,
Here a frontend work to for having Time and date in UI

![image](https://github.com/LOGESH-B/ChromeLandingPage/assets/86541143/1b6bf59d-a3f8-4da6-9c1d-713b38ca6530)

Any other creative features are also welcomed put it hear as comment

**Comment by HamzaFarooqArif** [comment]
I want to work on this feature. please assign it to me

**Comment by LOGESH-B** [comment]
@HamzaFarooqArif 
Great Work!
Your contribution helps us a lot.
