### ISSUE TITLE
Create a swap icon for toggle the time

### ISSUE THREAD

**Issue by LOGESH-B** [LOGESH-B/ChromeLandingPage#8]
Create a swap icon
Function:
* Swap icon toggle the railway timing to normal timing and vice versa

**Note: Icon can image or svg that should be downloaded in the project directories(Choose your own swap icon)**
![Group 2](https://github.com/LOGESH-B/ChromeLandingPage/assets/86541143/201ba3b3-3b27-4dda-9c4b-68359404d788)

**Comment by MRodriguez-M** [comment]
Hi, can you please assign this to me? I would like to work on this task

**Comment by LOGESH-B** [comment]
> Hi, can you please assign this to me? I would like to work on this task
@MRodriguez-M  Yes,Sure

**Comment by LOGESH-B** [comment]
Hii @MRodriguez-M 
Thanks for your contribution 🧑‍💻
